spring.application.name=skin_profile_system

spring.datasource.url=jdbc:postgresql://ep-mute-mode-at18v9oi-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=izzkwzabaahqwtql


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info
management.health.mail.enabled=false

server.port=8080