spring.application.name=skin_profile_system

spring.datasource.url=jdbc:mysql://localhost:3306/skin_profile_db
spring.datasource.username=root
spring.datasource.password=@Mbatsane2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mbatsicarmina@gmail.com
spring.mail.password=@Mbatsane2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080